### ISSUE TITLE
Missing parameters in GEMM layer when training with simple ONNX models 

### ISSUE THREAD

**Issue by nfnt** [ENOT-AutoDL/onnx2torch#132]
I'm using `onnx2torch` to  train (rather simple) models provided as ONNX files. This worked fine with my models for `onnx2torch` version 1.5.2 but it seems that the changes in 1.5.3 around GEMM broke my workflow. The model returned from `onnx2torch.convert` since that version is missing its parameters as provided by `model.parameters()` to an optimizer. To reproduce here's an example, converting a simple Pytorch model to ONNX, then back to Pytorch using `onnx2torch`, then training this model:

```python
import io

import onnx2torch
import torch

import onnx


def fit(dataset, model, loss_fn, optimizer):
    for inputs, target in dataset:
        pred = model(inputs)
        loss = loss_fn(pred, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f"loss: {loss.item()}")


model = torch.nn.Sequential(
    torch.nn.Linear(20, 10),
    torch.nn.ReLU(),
    torch.nn.Linear(10, 1),
)

epochs = 2
batch_size = 16

model_bytes = io.BytesIO()
torch.onnx.export(
    model,
    torch.randn(batch_size, 20),
    model_bytes,
    do_constant_folding=False,
    training=torch.onnx.TrainingMode.TRAINING,
)

onnx_model = onnx2torch.convert(onnx.load_model_from_string(model_bytes.getvalue()))

inputs = torch.randn(32, 20)
target = torch.randn(32, 1)

ds = torch.utils.data.TensorDataset(inputs, target)
dataset = torch.utils.data.DataLoader(ds, batch_size=batch_size)

loss_fn = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(onnx_model.parameters())

for epoch in range(epochs):
    print(f"epoch: {epoch+1}")
    fit(dataset, onnx_model, loss_fn, optimizer)

```

This is using [Pytorch](https://pypi.org/project/torch/) 1.3.1 and [ONNX](https://pypi.org/project/onnx/) 1.13.0. It will work as expected with `onnx2torch` 1.5.2 but fails starting with 1.5.3.

**Comment by senysenyseny16** [comment]
Hello, @nfnt.

Could you describe the problem in more detail? I can't reproduce it.

```bash
❯ pip list | grep torch
torch                         1.13.1+cu116
torchaudio                    0.13.1+cu116
torchvision                   0.14.1+cu116

❯ pip list | grep onnx
onnx                          1.13.0
```

Also I added the following code to your script:
```python3
for param in onnx_model.parameters():
    print(f'{param.shape}')
```

Output for `onnx2torch==1.5.2`:
```
torch.Size([10, 20])
torch.Size([10])
torch.Size([1, 10])
torch.Size([1])
```

Output for `onnx2torch==1.5.3`:
```
torch.Size([10, 20])
torch.Size([10])
torch.Size([1, 10])
torch.Size([1])
```

The parameter sets are the same.

**Comment by nfnt** [comment]
Interesting, I tested again, both in my prototyping environment (on macOS, Python 3.10.10) and production environment (Linux, Python 3.9.16) in fresh virtual environments. In both environments I get the same error with onnx2torch > 1.5.2:
```
Traceback (most recent call last):
  File "/work/main.py", line 51, in <module>
    optimizer = torch.optim.Adam(onnx_model.parameters())
  File "/usr/local/lib/python3.9/site-packages/torch/optim/adam.py", line 137, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/usr/local/lib/python3.9/site-packages/torch/optim/optimizer.py", line 61, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```
with onnx2torch 1.5.2 the output is the same as yours:
```
torch.Size([10, 20])
torch.Size([10])
torch.Size([1, 10])
torch.Size([1])
```

In both cases I installed Pytorch with pip, i.e. on Linux
```
$ pip list | grep torch
torch                    1.13.1
torchvision              0.14.1
$ pip list | grep onnx
onnx                     1.13.0
```

**Comment by senysenyseny16** [comment]
I created fresh venv for `Python3.9` and only installed `torch` and `onnx2torch`:

```bash
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
pip3 install onnx2torch==1.5.3
```

```
❯ python3 --version
Python 3.9.16

❯ pip list
Package            Version
------------------ ----------
certifi            2022.12.7
charset-normalizer 3.0.1
idna               3.4
numpy              1.24.2
onnx               1.13.0
onnx2torch         1.5.3
Pillow             9.4.0
pip                20.3.4
pkg-resources      0.0.0
protobuf           3.20.3
requests           2.28.2
setuptools         44.1.1
torch              1.13.1+cpu
torchaudio         0.13.1+cpu
torchvision        0.14.1+cpu
typing-extensions  4.4.0
urllib3            1.26.14
```

It works.

Could you please show `pip list` in your environment? Is it venv or conda env?

**Comment by nfnt** [comment]
It's a regular venv, not using conda. All of this running in an unmodified `python:3.9` Docker container. Same result when installing the exact same packages as you do:
```
$ pip3 list
pip3 list
Package            Version
------------------ ----------
certifi            2022.12.7
charset-normalizer 3.0.1
idna               3.4
numpy              1.24.2
onnx               1.13.0
onnx2torch         1.5.3
Pillow             9.4.0
pip                22.0.4
protobuf           3.20.3
requests           2.28.2
setuptools         58.1.0
torch              1.13.1+cpu
torchvision        0.14.1+cpu
typing_extensions  4.4.0
urllib3            1.26.14
wheel              0.38.4
$ python3 main.py 
Traceback (most recent call last):
  File "/work/main.py", line 51, in <module>
    optimizer = torch.optim.Adam(onnx_model.parameters())
  File "/usr/local/lib/python3.9/site-packages/torch/optim/adam.py", line 137, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/usr/local/lib/python3.9/site-packages/torch/optim/optimizer.py", line 61, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

**Comment by senysenyseny16** [comment]
It is very strange :)

```bash
❯ docker run --rm --gpus all -ti -v $(pwd):/io python:3.9 bash
root@07622ad61af5:/# python3 -m venv venv39
root@07622ad61af5:/# source venv39/bin/activate
(venv39) root@07622ad61af5:/# python3 --version
Python 3.9.16
(venv39) root@07622ad61af5:/# pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading https://download.pytorch.org/whl/cpu/torch-1.13.1%2Bcpu-cp39-cp39-linux_x86_64.whl (199.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 MB 8.0 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.14.1%2Bcpu-cp39-cp39-linux_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 10.0 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cpu/torchaudio-0.13.1%2Bcpu-cp39-cp39-linux_x86_64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 9.8 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting numpy
  Downloading numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 14.3 MB/s eta 0:00:00
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.4.0-cp39-cp39-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 14.5 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 1.9 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 KB 7.7 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 5.5 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 6.6 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 KB 20.5 MB/s eta 0:00:00
Installing collected packages: charset-normalizer, urllib3, typing-extensions, pillow, numpy, idna, certifi, torch, requests, torchvision, torchaudio
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 numpy-1.24.2 pillow-9.4.0 requests-2.28.2 torch-1.13.1+cpu torchaudio-0.13.1+cpu torchvision-0.14.1+cpu typing-extensions-4.4.0 urllib3-1.26.14
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the '/venv39/bin/python3 -m pip install --upgrade pip' command.
(venv39) root@07622ad61af5:/# pip3 install onnx2torch==1.5.3
Collecting onnx2torch==1.5.3
  Downloading onnx2torch-1.5.3-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 KB 759.6 kB/s eta 0:00:00
Requirement already satisfied: torchvision>=0.9.0 in /venv39/lib/python3.9/site-packages (from onnx2torch==1.5.3) (0.14.1+cpu)
Collecting onnx>=1.9.0
  Downloading onnx-1.13.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 24.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.4 in /venv39/lib/python3.9/site-packages (from onnx2torch==1.5.3) (1.24.2)
Requirement already satisfied: torch>=1.8.0 in /venv39/lib/python3.9/site-packages (from onnx2torch==1.5.3) (1.13.1+cpu)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /venv39/lib/python3.9/site-packages (from onnx>=1.9.0->onnx2torch==1.5.3) (4.4.0)
Collecting protobuf<4,>=3.20.2
  Downloading protobuf-3.20.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 24.9 MB/s eta 0:00:00
Requirement already satisfied: requests in /venv39/lib/python3.9/site-packages (from torchvision>=0.9.0->onnx2torch==1.5.3) (2.28.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /venv39/lib/python3.9/site-packages (from torchvision>=0.9.0->onnx2torch==1.5.3) (9.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (1.26.14)
Installing collected packages: protobuf, onnx, onnx2torch
Successfully installed onnx-1.13.0 onnx2torch-1.5.3 protobuf-3.20.3
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the '/venv39/bin/python3 -m pip install --upgrade pip' command.
(venv39) root@07622ad61af5:/# cd io/
(venv39) root@07622ad61af5:/io# python3 gemm.py 
torch.Size([10, 20])
torch.Size([10])
torch.Size([1, 10])
torch.Size([1])
epoch: 1
loss: 0.9923501014709473
loss: 0.9108536243438721
epoch: 2
loss: 0.9763751029968262
loss: 0.9044812917709351
```

**Comment by nfnt** [comment]
Strange indeed, here's the same on my side:
```
docker run --rm -it -v$PWD:/work python:3.9 /bin/bash
root@4abaa9494de4:/# python3 -m venv venv39
root@4abaa9494de4:/# source venv39/bin/activate
(venv39) root@4abaa9494de4:/# python3 --version
Python 3.9.16
(venv39) root@4abaa9494de4:/# pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading https://download.pytorch.org/whl/cpu/torch-1.13.1%2Bcpu-cp39-cp39-linux_x86_64.whl (199.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 MB 4.0 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.14.1%2Bcpu-cp39-cp39-linux_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 7.0 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cpu/torchaudio-0.13.1%2Bcpu-cp39-cp39-linux_x86_64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 7.3 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.4.0-cp39-cp39-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 6.8 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 11.7 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 6.9 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 10.2 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 KB 10.7 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 KB 8.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 8.6 MB/s eta 0:00:00
Installing collected packages: charset-normalizer, urllib3, typing-extensions, pillow, numpy, idna, certifi, torch, requests, torchvision, torchaudio
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 numpy-1.24.2 pillow-9.4.0 requests-2.28.2 torch-1.13.1+cpu torchaudio-0.13.1+cpu torchvision-0.14.1+cpu typing-extensions-4.4.0 urllib3-1.26.14
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the '/venv39/bin/python3 -m pip install --upgrade pip' command.
(venv39) root@4abaa9494de4:/# pip3 install onnx2torch==1.5.3
Collecting onnx2torch==1.5.3
  Downloading onnx2torch-1.5.3-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 KB 4.2 MB/s eta 0:00:00
Requirement already satisfied: torchvision>=0.9.0 in /venv39/lib/python3.9/site-packages (from onnx2torch==1.5.3) (0.14.1+cpu)
Requirement already satisfied: numpy>=1.16.4 in /venv39/lib/python3.9/site-packages (from onnx2torch==1.5.3) (1.24.2)
Requirement already satisfied: torch>=1.8.0 in /venv39/lib/python3.9/site-packages (from onnx2torch==1.5.3) (1.13.1+cpu)
Collecting onnx>=1.9.0
  Downloading onnx-1.13.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 7.1 MB/s eta 0:00:00
Collecting protobuf<4,>=3.20.2
  Downloading protobuf-3.20.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.2.1 in /venv39/lib/python3.9/site-packages (from onnx>=1.9.0->onnx2torch==1.5.3) (4.4.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /venv39/lib/python3.9/site-packages (from torchvision>=0.9.0->onnx2torch==1.5.3) (9.4.0)
Requirement already satisfied: requests in /venv39/lib/python3.9/site-packages (from torchvision>=0.9.0->onnx2torch==1.5.3) (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /venv39/lib/python3.9/site-packages (from requests->torchvision>=0.9.0->onnx2torch==1.5.3) (1.26.14)
Installing collected packages: protobuf, onnx, onnx2torch
Successfully installed onnx-1.13.0 onnx2torch-1.5.3 protobuf-3.20.3
WARNING: You are using pip version 22.0.4; however, version 23.0 is available.
You should consider upgrading via the '/venv39/bin/python3 -m pip install --upgrade pip' command.
(venv39) root@4abaa9494de4:/# cd /work/
(venv39) root@4abaa9494de4:/work# python3 main.py 
Traceback (most recent call last):
  File "/work/main.py", line 48, in <module>
    optimizer = torch.optim.Adam(onnx_model.parameters())
  File "/venv39/lib/python3.9/site-packages/torch/optim/adam.py", line 137, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/venv39/lib/python3.9/site-packages/torch/optim/optimizer.py", line 61, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```
This is running the unmodified code I posted above as `main.py`.

**Comment by senysenyseny16** [comment]
@nfnt,

I was able to reproduce.
The problem is in [this](https://github.com/ENOT-AutoDL/onnx2torch/commit/03c764e89da029276883fcc9acab2770d163c9cb) commit, [fix](https://github.com/ENOT-AutoDL/onnx2torch/commit/0fc83d173bf80d8886b91c657abdcc32ad4e0e46) already in master, but not released yet.


Thanks for your help, we will release a new version as soon as possible.

**Comment by senysenyseny16** [comment]
released: https://pypi.org/project/onnx2torch/1.5.6/

**Comment by nfnt** [comment]
Thanks for the fast fix! I can confirm that this fixes the issue on my side. Therefore I'm closing this issue as resolved.
