### ISSUE TITLE
require to support operator 'ArgMax'

### ISSUE THREAD

**Issue by Lin-Tao-AI** [ENOT-AutoDL/onnx2torch#147]
Met the following error, hope to support operator 'ArgMax', thanks

Traceback (most recent call last):
  File "anna_onnx2torch.py", line 38, in <module>
    torch_model_1 = convert(onnx_model_path)
  File "/home/lin/anaconda3/envs/anna/lib/python3.8/site-packages/onnx2torch/converter.py", line 104, in convert
    converter = get_converter(
  File "/home/lin/anaconda3/envs/anna/lib/python3.8/site-packages/onnx2torch/node_converters/registry.py", line 69, in get_converter
    raise NotImplementedError(f'Converter is not implemented ({description})')
NotImplementedError: Converter is not implemented (OperationDescription(domain='', operation_type='ArgMax', version=12))

**Comment by JohnMasoner** [comment]
Hey @Lin-Tao-AI ,

I'm already developing this operator. Actually I'm having some problems, but I think I should solve it soon.

I think we will support it soon.

**Comment by senysenyseny16** [comment]
Implemented: https://github.com/ENOT-AutoDL/onnx2torch/releases/tag/v1.5.15
