### ISSUE TITLE
NotImplementedError: "SAME_UPPER" auto_pad is not implemented

### ISSUE THREAD

**Issue by cosonjia** [ENOT-AutoDL/onnx2torch#148]
I met the NotImplementedError 
When I convert  onnx model yolov3-12.onnx (https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/yolov3/model/yolov3-12.onnx).

 ERROR:

```
Traceback (most recent call last):
  File "/home/anna/tools/converter/onnx2pytorch.py", line 157, in <module>
    model_converted = onnx2pytorch(args.onnx_file, verify=args.verify,
  File "/home/anna/tools/converter/onnx2pytorch.py", line 112, in onnx2pytorch
    torch_model = convert(onnx_model)
  File "/home/anna/anaconda3/envs/pytorch112-cuda116-py38/lib/python3.8/site-packages/onnx2torch/converter.py", line 110, in convert
    torch_module, onnx_mapping = converter(onnx_node, onnx_graph)
  File "/home/anna/anaconda3/envs/pytorch112-cuda116-py38/lib/python3.8/site-packages/onnx2torch/node_converters/conv.py", line 48, in _
    padding, input_padding_module = onnx_auto_pad_to_torch_padding(
  File "/home/anna/anaconda3/envs/pytorch112-cuda116-py38/lib/python3.8/site-packages/onnx2torch/utils/padding.py", line 33, in onnx_auto_pad_to_torch_padding
    raise NotImplementedError(f'"{auto_pad}" auto_pad is not implemented')
NotImplementedError: "SAME_UPPER" auto_pad is not implemented

```

onnx2torch version: 1.5.6

Please fix the wrong import error and wrong error messages.

**Comment by shihtzu-717** [comment]
I have same error...

**Comment by senysenyseny16** [comment]
@ivkalgin
