### ISSUE TITLE
Can't convert BERT model

### ISSUE THREAD

**Issue by redthing1** [ENOT-AutoDL/onnx2torch#158]
Using the sample code in the README:

Trying to convert this model: https://huggingface.co/1-800-BAD-CODE/sentence_boundary_detection_multilang/blob/main/sbd_49lang_bert_small.onnx

This is a BERT based model.

```
>>> onnx_model_path = '/home/user/Downloads/sentence_boundary_detection_multilang/sbd_49lang_bert_small.onnx'
>>> torch_model_1 = convert(onnx_model_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.11/site-packages/onnx2torch/converter.py", line 104, in convert
    converter = get_converter(
                ^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/onnx2torch/node_converters/registry.py", line 69, in get_converter
    raise NotImplementedError(f'Converter is not implemented ({description})')
NotImplementedError: Converter is not implemented (OperationDescription(domain='', operation_type='LayerNormalization', version=17))
>>> 
```

I get the above error.

**Comment by senysenyseny16** [comment]
related PR: #143

**Comment by senysenyseny16** [comment]
#165

**Comment by senysenyseny16** [comment]
@redthing1 

released: https://github.com/ENOT-AutoDL/onnx2torch/releases/tag/v1.5.9

**Comment by senysenyseny16** [comment]
Feel free to reopen if there are any problems or questions.
