### ISSUE TITLE
Unable to successfully convert retinanet R50

### ISSUE THREAD

**Issue by NTUTshaofong** [ENOT-AutoDL/onnx2torch#185]
Traceback (most recent call last):
  File "/home/li/testcode/tool2/convert_dataloader.py", line 490, in <module>
    fp_model = copy.deepcopy(convert(onnx_model).to(device))  

  File "/home/li/.local/lib/python3.6/site-packages/onnx2torch/converter.py", line 107, in convert
    version=version,
  File "/home/li/.local/lib/python3.6/site-packages/onnx2torch/node_converters/registry.py", line 69, in get_converter
    raise NotImplementedError(f'Converter is not implemented ({description})')
NotImplementedError: Converter is not implemented (OperationDescription(domain='', operation_type='NonZero', version=13))

I tried changing the opset but apparently it doesn't support non-zero operators. Can you tell me the details of the method the authors originally tested ? thanks

**Comment by andreysher** [comment]
Hi @NTUTshaofong, we test convertion on the model retinanet_r50_fpn from the MMDetection framework. You can find it in our [tests](https://github.com/ENOT-AutoDL/onnx2torch/blob/main/tests/models/models_test.py#L72). You can also download our ONNX by the following [link](https://gitlab.expasoft.com/p.ivanov/onnx2torch_data/-/raw/main/models_for_tests/detection/retinanet_r50_fpn.onnx).

Can you please provide the details about your checkpoint?
