### ISSUE TITLE
NotImplementedError: Converter is not implemented (OperationDescription(domain='', operation_type='Loop', version=13))

### ISSUE THREAD

**Issue by pzy2000** [ENOT-AutoDL/onnx2torch#204]
Traceback (most recent call last):
  File "issue_onnx2torch_002.py", line 15, in <module>
    torch_model = convert(onnx_model_path)
  File "/opt/conda/envs/tf2onnx/lib/python3.7/site-packages/onnx2torch/converter.py", line 107, in convert
    version=version,
  File "/opt/conda/envs/tf2onnx/lib/python3.7/site-packages/onnx2torch/node_converters/registry.py", line 69, in get_converter
    raise NotImplementedError(f'Converter is not implemented ({description})')
NotImplementedError: Converter is not implemented (OperationDescription(domain='', operation_type='Loop', version=13))

run the below codes to reproduce the above issue:

import numpy as np
import torch
from onnx2torch import convert

def _init_input(input_shape):
    input_shape = list(input_shape)
    input_shape[0] = 10
    input_shape = tuple(input_shape)
    input = np.random.rand(*input_shape)
    return input

onnx_model_path = "lstm0-sinewave_origin.onnx"
torch_model = convert(onnx_model_path)

**Comment by pzy2000** [comment]
the onnx file can be downloaded here:
[lstm0-sinewave_origin.zip](https://github.com/ENOT-AutoDL/onnx2torch/files/14616115/lstm0-sinewave_origin.zip)

**Comment by Yogesh-45** [comment]
Hi @pzy2000 ,
Were you able to find solution for it?
