### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by KYE2138** [ENOT-AutoDL/onnx2torch#45]
when import library

```
>>> from onnx2torch import convert
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/__init__.py", line 1, in <module>
    from onnx2torch.converter import convert
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/converter.py", line 13, in <module>
    from onnx2torch.node_converters import get_converter
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/node_converters/__init__.py", line 1, in <module>
    from onnx2torch.node_converters.activations import *
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/node_converters/activations.py", line 6, in <module>
    from onnx2torch.node_converters.registry import add_converter
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/node_converters/registry.py", line 7, in <module>
    from onnx2torch.onnx_graph import OnnxGraph
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/onnx_graph.py", line 10, in <module>
    from onnx2torch.onnx_node import OnnxNode
  File "/usr/bin/python3/lib/python3.6/site-packages/onnx2torch/onnx_node.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

This is `pip list`
```
Package                 Version
----------------------- ---------------------
absl-py                 1.0.0
cachetools              4.2.4
certifi                 2021.10.8
charset-normalizer      2.0.12
dataclasses             0.8
easydict                1.9
google-auth             1.35.0
google-auth-oauthlib    0.4.6
grpcio                  1.44.0
idna                    3.3
importlib-metadata      4.8.3
Markdown                3.3.6
numpy                   1.18.5
oauthlib                3.2.0
onnx                    1.11.0
onnx2torch              1.2.5
Pillow                  7.1.2
pip                     21.3.1
protobuf                3.19.4
pyasn1                  0.4.8
pyasn1-modules          0.2.8
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
setuptools              59.5.0
six                     1.16.0
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
thop                    0.0.31.post2005241907
torch                   1.9.0+cu111
torchaudio              0.9.0
torchvision             0.10.0+cu111
tqdm                    4.46.1
typing_extensions       4.1.1
urllib3                 1.26.9
Werkzeug                2.0.3
wheel                   0.37.1
zipp                    3.6.0
```

Is the python version(3.6.9) too old to use `from __future__ import annotations` ?
I need the version to run another AutoML project. Thanks.

**Comment by KYE2138** [comment]
I updated the python version to 3.7 to fix it.
